//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: Guid("fab4c86e-fa7a-453c-acb6-90e229411626")]
[assembly: AssemblyTitle("Contexteer")]
[assembly: AssemblyDescription("A framework for contexts")]
[assembly: AssemblyCompany("Contexteer")]
[assembly: AssemblyProduct("Contexteer")]
[assembly: AssemblyCopyright("Copyright - Contexteer 2012")]
[assembly: AssemblyVersion("0.1.0")]
[assembly: AssemblyFileVersion("0.1.0")]
[assembly: AssemblyInformationalVersion("0.1.0")]
[assembly: AssemblyDelaySign(false)]


